#! / usr / bin / env python
# - * - codificação: utf-8 - * -

 solicitações de importação , sys , re

dados  = { 'nome' : '' , 'renach' : '' , 'cpf' : '' , 'dataNascimento' : '' , 'local' : '' , 'cfc' : '' , 'resultado' : ' ' , ' data ' : ' ' , ' hora ' : ' ' }

def  get_dados ( conteúdo ): # Regex tags XML
    nome  =  re . search ( '<nome> (. *) </nome>' , conteúdo ). grupo ( 0 ). substituir ( '<nome>' , '' ). substituir ( '</nome>' , '' )   
    renach  =  re . search ( '<renach> (. *) </renach>' , conteúdo ). grupo ( 0 ). substituir ( '<renach>' , '' ). substituir ( '</renach>' , '' )  
    cpf  =  re . pesquisa ( '<cpf> (. *) </cpf>' , conteúdo ). grupo ( 0 ). substituir ( '<cpf>' , '' ). substituir ( '</cpf>' , '' )
    dataNascimento  =  re . search ( '<dataNascimento> (. *) </dataNascimento>' , conteúdo ). grupo ( 0 ). substituir ( '<dataNascimento>' , '' ). substituir ( '</dataNascimento>' , '' )
    
    local  =  re . pesquisa ( '<local> (. *) </local>' , conteúdo ). grupo ( 0 ). substituir ( '<local>' , '' ). substituir ( '</local>' , '' )
   
    cfc  =  re . pesquisa ( '<cfc> (. *) </cfc>' , conteúdo ). grupo ( 0 ). substituir ( '<cfc>' , '' ). substituir ( '</cfc>' , '' )
    resultado  =  re . search ( '<resultado> (. *) </resultado>' , conteúdo ). grupo ( 0 ). substituir ( '<resultado>' , '' ). substituir ( '</resultado>' , '' )
    dados  =  re . search ( '<data> (. *) </data>' , conteúdo ). grupo ( 0 ). substituir ( '<dados>' , '' ). substituir ( '</data>' , '' )
    hora  =  re . search ( '<hora> (. *) </hora>' , conteúdo ). grupo ( 0 ). substituir ( '<hora>' , '' ). substituir ( '</hora>' , '' )
    dados [ 'nome' ], dados [ 'renach' ], dados [ 'cpf' ], dados [ 'dataNascimento' ], dados [ 'local' ], dados [ 'cfc' ], dados [ 'resultado' ], dados [ 'data' ], dados [ 'hora' ] =  nome , renach , cpf , dataNascimento , local , cfc ,resultado ,dados , hora

if  __name__  ==  "__main__" :
    se  len ( sys . argv ) >  1 :
        configs  = { 'api_getran' : 'http://getran.detran.df.gov.br/getranServicos/ConsultaHabilitacaoWS?wsdl' , 'cpf' : sys . argv [ 1 ], 'token' : 'TKN832JHGSI2937MNGHSJ9987' , 'user_agent' : 'ksoap2-android / 2.6.0 +' }
        data  =  '<v: Envelope xmlns: i = "http://www.w3.org/2001/XMLSchema-instance" xmlns: d = "http://www.w3.org/2001/XMLSchema" xmlns: c = "http://schemas.xmlsoap.org/soap/encoding/" xmlns: v = "http://schemas.xmlsoap.org/soap/envelope/"> '
        data  + =  '<v: Header /> <v: Body> <n0: consultarBanca id = "o0" c: root = "1" xmlns: n0 = "http: //ws.habilitacao.site.servicos.getran. searchtecnologia.com.br / "> '
        data  + =  '<cpf i: type = "d: string">' + configs [ 'cpf' ] + '</cpf>'
        data  + =  '<token i: type = "d: string">' + configs [ 'token' ] + '</token>'
        data  + =  '</ n0: consultarBanca> </ v: Body> </ v: Envelope>'
        headers  = { 'User-Agent' : configs [ 'user_agent' ], 'SOAPAction' : 'http://getran.detran.df.gov.br/getranServicos/' , 'Content-Type' : 'text / xml; charset = utf-8 ' }
        req  =  solicitações . post ( configs [ 'api_getran' ], data = data , headers = headers )
        get_dados ( req . content ) # Chama a função get_dados e retorna os dados solicitados.
        imprimir  'Nome completo:' , dados [ 'nome' ]
        imprimir  'CPF:' , dados [ 'cpf' ]
        imprimir  'Renach:' , dados [ 'renach' ]
        imprimir  'Data de nascimento:' , dados [ 'dataNascimento' ]
        imprimir  'CFC:' , dados [ 'cfc' ]
        print  'Data:' , dados [ 'data' ], 'Hora:' , dados [ 'hora' ]
        imprimir  'Resultado:' , dados [ 'resultado' ]
    mais :
        print  "[!] Executar o script junto com o cpf sem caracter: ./getran.py <cpf> | ./getran.py 1234567891011"
